server:
  minio:
    url: http://127.0.0.1:9000
    id: minioadmin
    key: minioadmin
  spring:
    url: http://127.0.0.1:8080
client:
  upload-db-path: database/upload.db
  download-db-path: database/download.db
  transport-db-path: database/transport.db
  save-size: 52428800 # 50M自动保存
  update-time: 1000 # 1s自动刷新
  uploader-length: 5 
  download-path: 