server:
  url: http://127.0.0.1:9000
  id: minioadmin
  key: minioadmin
client:
  upload-db-path: database/upload.db
  download-db-path: database/download.db
  transport-db-path: database/transport.db
  save-size: 52428800 # 50M自动保存
  update-time: 250 # 50M自动保存